name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Build and push Docker image
      run: |
        az acr login --name ${{ env.AZURE_REGISTRY }}
        docker build -t ${{ env.AZURE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ env.AZURE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Terraform Init
      run: terraform init -input=false -force-copy
      working-directory: ./terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
        -var="image_tag=${{ github.sha }}" \
        -var="acr_name=${{ env.AZURE_REGISTRY }}" \
        -var="image_name=${{ env.IMAGE_NAME }}"
      working-directory: ./terraform